language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
services: mongodb
before_install:
   - cpanm -n Dist::Zilla
   - dzil authordeps | cpanm -n
   - dzil build
   - cd ./Mongoose*
